### ISSUE TITLE
Error in the demo

### ISSUE THREAD

**Issue by heoa** [paasim/shinyproj#1]
Hello,
I tried the demo but getting the error:

> Error in quantile.default(bs - bf, c(a, 1 - a), names = F) : 
>   missing values and NaN's not allowed if 'na.rm' is FALSE

**Comment by paasim** [comment]
Hi,

Thanks for the message. This is due to changes in projpred  - at least since version 0.8 it uses only a part of the data for evaluating LOO by default while shinyproj relied on it evaluating the log predictive density on every observation. This can be fixed by setting the nloo-argument of cv_varsel to the number of observations.

I updated the readme on the dev-branch (see 42301035578dcbf2ec329609769874aa72392ccb) which should now contain a working example.
